model_list:
  - model_name: qwen ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: hosted_vllm/qwen
      api_base: http://10.142.6.40:40404/v1
      api_key: "111" # does os.getenv("AZURE_API_KEY_EU")
